modules:
  mode: blacklist # blacklist, whitelist or disabled
  fail:
    # Time in ticks that the server waits for the client to update its modules if any disallowed ones were registered.
    delay: 40
    kick: true
    kick-message: '&6MPK &8> &cDisallowed modules were detected on your client:\n&e%modules%.\n&7Please try rejoining.'
    notify: true
    notify-message: '&6MPK &8> &cDisallowed modules were detected for &f%player%&c: &e%modules%'
  entries:
    - "mpkmacros"