name: MPKBukkitAPI
version: ${version}
main: io.github.kurrycat.mpknetapi.bukkit.MPKApiPlugin
authors: ['devcody']
commands:
  mpk:
    description: Main command for the MPK Bukkit plugin
    usage: /mpk help
    permission: mpknetapi.bukkit.command